// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/wajox/clonegopkg/internal/app/dependencies"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	container := &dependencies.Container{}
	application := &Application{
		Container: container,
	}
	return application, nil
}
